session_timeout_minutes = 60
max_sessions_per_user = 10
mcp_servers_config = "/home/zhengyangliang/videochameleon/univa/config/mcp_configs.json"
prompt_dir = "/home/zhengyangliang/videochameleon/univa/prompts"
mcp_tools_path = "/home/zhengyangliang/videochameleon/univa"
plan_model_provider = "openai"
plan_model_id = "gpt-5-2025-08-07"
plan_model_base_url = ""
plan_model_extra_params = ""
act_model_provider = "openai"
act_model_id = "gpt-5-2025-08-07"
act_model_base_url = ""
act_model_extra_params = ""
proxy_host = ""
proxy_port = ""

[mcp_config]
